---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gy.
--- DateTime: 2023/11/8 17:10
---

local prefixKey = "gy-"
local pkId = "test1"

local function getPkBaseInfo(prefixKey, pkId)
    local redisKey = prefixKey .. tostring(pkId)
    local baseInfoObject = {}
    local infoRedis = redis.call("hgetall", redisKey);
    if infoRedis == nil or next(infoRedis) == nil then
        baseInfoObject["pkId"] = tonumber(pkId)
        baseInfoObject["awardLevel"] = 1
        baseInfoObject["awardKey"] = "test1"
        baseInfoObject["awardItem"] = ""
        baseInfoObject["baseBlood"] = 0
        baseInfoObject["rids"] = ""
        baseInfoObject["pkStatus"] = 0
        baseInfoObject["createTime"] = 0
        baseInfoObject["readyTime"] = 0
        baseInfoObject["startTime"] = 0
        baseInfoObject["endTime"] = 0
    else
        --for k, v in pairs(infoRedis) do
        --    if k % 2 == 1 then
        --        baseInfoObject[v] = infoRedis[k + 1]
        --    end
        --end
        for i = 1, #infoRedis, 2 do
            baseInfoObject[infoRedis[i]] = infoRedis[i + 1]
        end
    end
    return baseInfoObject,infoRedis
end

local obj,redisObj = getPkBaseInfo(prefixKey, pkId)
return {0,cjson.encode(obj),cjson.encode(redisObj)}