---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gy.
--- DateTime: 2023/11/2 19:56
---
-- 调试配置相关代码，实际使用不需要 start--
package.cpath = package.cpath .. ';/Users/gy/Library/Application Support/JetBrains/IntelliJIdea2023.2/plugins/EmmyLua/debugger/emmy/mac/x64/?.dylib'
local dbg = require('emmy_core')
dbg.tcpConnect('localhost', 9966)

-- redis相关配置
local cjson = require 'cjson'
local redis = require 'redis'
local defaults = {
    host = '127.0.0.1',
    port = 6379,
    tcp_nodelay = true,
    path = nil
}
client = redis.connect(defaults)
-- 需要密码是启用
-- client:auth('wsd_data@douyu123')

redis.call = function(cmd, ...)
    return assert(load('return client:' .. string.lower(cmd) .. '(...)'))(...)
end
-- 调试配置相关代码，实际使用不需要 end--


local KEYS = { "test1", "test2" }
local ARGV = { "1", '{\"age\":\"23\",\"name\":\"test\"}' }

local baseInfo = "{\"pkId\":0,\"awardLevel\":0,\"awardKey\":\"awardKey_46fc60386ee2\",\"awardItem\":{\"awardKey\":\"awardKey_6714e667f0b8\",\"awardList\":[{\"type\":0,\"awardType\":0,\"awardId\":0,\"awardStock\":0}]},\"baseBlood\":0,\"rids\":[0],\"pkStatus\":0,\"createTime\":0,\"readyTime\":0,\"startTime\":0,\"endTime\":0,\"joinRid\":0,\"serverTime\":0}"
local baseInfoObj = cjson.decode(baseInfo)
local rids = baseInfoObj["rids"]
local length = #rids
print(length)

local value = redis.call("GET", "key1")
print(value)

local queueListRedisKey = KEYS[1]
print(queueListRedisKey)

local userInfoObj = cjson.decode(ARGV[2])
print(cjson.encode(userInfoObj))

local result = redis.call("HINCRBY", "gy-test-1113", "test1", 1)
print(result)