server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 45s
  application:
    name: metrics-demo
  jackson:
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

# 暴露prometheus指标
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
        pushgateway:
          enabled: true
          base-url: http://dev.pushgateway:19091
          push-rate: 10s
          shutdown-operation: push
      jmx:
        enabled: true
    tags:
      application: ${spring.application.name}
      hostname: ${POD_NAME:${HOSTNAME:${spring.application.name}:${server.port}}}
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /metrics