server:
  port: 8082
  tomcat:
    max-threads: 500
    min-spare-threads: 50

spring:
  jackson:
    default-property-inclusion: non_null
#    visibility:
#      all: any
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345678
    lettuce:
      pool:
        max-active: 200
        max-wait: 2000ms
        max-idle: 50
        min-idle: 10

#management:
#  endpoints:
#    web:
#      exposure:
#        #参考：https://docs.spring.io/spring-boot/docs/2.6.3/reference/html/actuator.html#actuator.endpoints
#        include: "health,info,metrics"
#  endpoint:
#    health:
#      show-details: always
#  info:
#    java:
#      enabled: true

# 暴露prometheus指标
management:
  security:
    enabled: false
  metrics:
    export:
#      prometheus:
#        enabled: true
#        pushgateway:
#          enabled: true
#          base-url: http://dev.pushgateway:19091
#          push-rate: 10s
      jmx:
        enabled: true
    tags:
      application: ${spring.application.name}
      hostname: ${POD_NAME:${HOSTNAME:${spring.application.name}:${server.port}}}
  health:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /metrics

limitCheck:
  limit: 3

